/*
################################################################################
# 2015-11-26 18:52:00 : genAsia.js generated from /home/phw/Documents/gits/lip6/metaGenBayes/metaGenBayes/test/config.yaml
#
# This file is generated by metaGenBayes 1.0.0 for node.js>0.10
#
# Do not make changes to this file unless you know what you are doing
# Please modify the configuration file (/home/phw/Documents/gits/lip6/metaGenBayes/metaGenBayes/test/config.yaml) instead.
################################################################################

*/

function getProbaForAsia(evs) {
  res=[];
  P0sachant= new Float32Array([0.009999999776482582, 0.9900000095367432]);
  P1sachant0= new Float32Array([0.05000000074505806, 0.949999988079071, 0.009999999776482582, 0.9900000095367432]);
  P2sachant1_4= new Float32Array([1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0]);
  P3sachant2= new Float32Array([0.9800000190734863, 0.019999999552965164, 0.05000000074505806, 0.949999988079071]);
  P4sachant5= new Float32Array([0.10000000149011612, 0.8999999761581421, 0.009999999776482582, 0.9900000095367432]);
  P5sachant= new Float32Array([0.5, 0.5]);
  P6sachant5= new Float32Array([0.6000000238418579, 0.4000000059604645, 0.30000001192092896, 0.699999988079071]);
  P7sachant6_2= new Float32Array([0.8999999761581421, 0.10000000149011612, 0.699999988079071, 0.30000001192092896, 0.800000011920929, 0.20000000298023224, 0.10000000149011612, 0.8999999761581421]);
// CPO BFSTAZ [2, 3] 1.0
  BFSTAZ= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    BFSTAZ[i] = 1.0;
// CPO XAYKYJ [2, 6, 7] 1.0
  XAYKYJ= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    XAYKYJ[i] = 1.0;
// CPO SUNBGR [0, 1] 1.0
  SUNBGR= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    SUNBGR[i] = 1.0;
// CPO ZZQCLE [1, 2, 4] 1.0
  ZZQCLE= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    ZZQCLE[i] = 1.0;
// CPO BPTROO [2, 5, 6] 1.0
  BPTROO= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    BPTROO[i] = 1.0;
// CPO YDOOJS [2, 4, 5] 1.0
  YDOOJS= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    YDOOJS[i] = 1.0;
// MUC SUNBGR 0 [0, 1]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      SUNBGR[i0*1+i1*2] *= P0sachant[i0*1.0];}}
// MUC SUNBGR 1 [0, 1]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      SUNBGR[i0*1+i1*2] *= P1sachant0[i0*2.0+i1*1.0];}}
// MUC ZZQCLE 2 [1, 2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        ZZQCLE[i0*1+i1*2+i2*4] *= P2sachant1_4[i0*4.0+i2*2.0+i1*1.0];}}}
// MUC BFSTAZ 3 [2, 3]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      BFSTAZ[i0*1+i1*2] *= P3sachant2[i0*2.0+i1*1.0];}}
// MUC YDOOJS 4 [2, 4, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        YDOOJS[i0*1+i1*2+i2*4] *= P4sachant5[i2*2.0+i1*1.0];}}}
// MUC BPTROO 5 [2, 5, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BPTROO[i0*1+i1*2+i2*4] *= P5sachant[i1*1.0];}}}
// MUC BPTROO 6 [2, 5, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BPTROO[i0*1+i1*2+i2*4] *= P6sachant5[i1*2.0+i2*1.0];}}}
// MUC XAYKYJ 7 [2, 6, 7]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        XAYKYJ[i0*1+i1*2+i2*4] *= P7sachant6_2[i0*4.0+i1*2.0+i2*1.0];}}}
// ASE smoking? EV_5 0 evs.get([5, 'smoking?'][1])
  EV_5= new Float32Array(evs['smoking?']);
// ASE visit_to_Asia? EV_0 0 evs.get([0, 'visit_to_Asia?'][1])
  EV_0= new Float32Array(evs['visit_to_Asia?']);
// ASE dyspnoea? EV_7 0 evs.get([7, 'dyspnoea?'][1])
  EV_7= new Float32Array(evs['dyspnoea?']);
// ASE positive_XraY? EV_3 0 evs.get([3, 'positive_XraY?'][1])
  EV_3= new Float32Array(evs['positive_XraY?']);
// MUL SUNBGR EV_0 [0, 1] ['0']
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
    SUNBGR[i0*1+i1*2] *= EV_0[i0*1];}}
// MUL BFSTAZ EV_3 [2, 3] ['3']
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
    BFSTAZ[i0*1+i1*2] *= EV_3[i1*1];}}
// MUL BPTROO EV_5 [2, 5, 6] ['5']
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BPTROO[i0*1+i1*2+i2*4] *= EV_5[i1*1];}}}
// MUL XAYKYJ EV_7 [2, 6, 7] ['7']
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        XAYKYJ[i0*1+i1*2+i2*4] *= EV_7[i2*1];}}}
// CPO CTVLKT [2, 5, 6] 1.0
  CTVLKT= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    CTVLKT[i] = 1.0;
// MUL CTVLKT BPTROO [2, 5, 6] [2, 5, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        CTVLKT[i0*1+i1*2+i2*4] *= BPTROO[i0*1+i1*2+i2*4];}}}
// CPO FOHMFI [2, 4, 5] 1.0
  FOHMFI= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    FOHMFI[i] = 1.0;
// MUL FOHMFI YDOOJS [2, 4, 5] [2, 4, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        FOHMFI[i0*1+i1*2+i2*4] *= YDOOJS[i0*1+i1*2+i2*4];}}}
// CPO ZKWJBN [1, 2, 4] 1.0
  ZKWJBN= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    ZKWJBN[i] = 1.0;
// MUL ZKWJBN ZZQCLE [1, 2, 4] [1, 2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        ZKWJBN[i0*1+i1*2+i2*4] *= ZZQCLE[i0*1+i1*2+i2*4];}}}
// CPO BAILMG [2, 4, 5] 1.0
  BAILMG= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    BAILMG[i] = 1.0;
// MUL BAILMG YDOOJS [2, 4, 5] [2, 4, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BAILMG[i0*1+i1*2+i2*4] *= YDOOJS[i0*1+i1*2+i2*4];}}}
// CPO AJSNYX [2, 6] 0.0
  AJSNYX= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    AJSNYX[i] = 0.0;
// MAR AJSNYX XAYKYJ [2, 6] [2, 6, 7]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        AJSNYX[i0*1+i1*2] += XAYKYJ[j0*4.0+i1*2.0+i0*1.0];}}}
// MUL BPTROO AJSNYX [2, 5, 6] [2, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BPTROO[i0*1+i1*2+i2*4] *= AJSNYX[i0*1+i2*2];}}}
// CPO USKGPZ [1] 0.0
  USKGPZ= new Float32Array(2);
  for(i=0;i<2;i++)
    USKGPZ[i] = 0.0;
// MAR USKGPZ SUNBGR [1] [0, 1]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      USKGPZ[i0*1] += SUNBGR[i0*2.0+j0*1.0];}}
// MUL ZZQCLE USKGPZ [1, 2, 4] [1]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        ZZQCLE[i0*1+i1*2+i2*4] *= USKGPZ[i0*1];}}}
// CPO WUIRBO [2, 4] 0.0
  WUIRBO= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    WUIRBO[i] = 0.0;
// MAR WUIRBO ZZQCLE [2, 4] [1, 2, 4]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        WUIRBO[i0*1+i1*2] += ZZQCLE[i1*4.0+i0*2.0+j0*1.0];}}}
// MUL YDOOJS WUIRBO [2, 4, 5] [2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        YDOOJS[i0*1+i1*2+i2*4] *= WUIRBO[i0*1+i1*2];}}}
// CPO OWMIBF [2, 5] 0.0
  OWMIBF= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    OWMIBF[i] = 0.0;
// MAR OWMIBF YDOOJS [2, 5] [2, 4, 5]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        OWMIBF[i0*1+i1*2] += YDOOJS[i1*4.0+j0*2.0+i0*1.0];}}}
// MUL BPTROO OWMIBF [2, 5, 6] [2, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BPTROO[i0*1+i1*2+i2*4] *= OWMIBF[i0*1+i1*2];}}}
// CPO CRJXSM [2] 0.0
  CRJXSM= new Float32Array(2);
  for(i=0;i<2;i++)
    CRJXSM[i] = 0.0;
// MAR CRJXSM BFSTAZ [2] [2, 3]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      CRJXSM[i0*1] += BFSTAZ[j0*2.0+i0*1.0];}}
// MUL BPTROO CRJXSM [2, 5, 6] [2]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BPTROO[i0*1+i1*2+i2*4] *= CRJXSM[i0*1];}}}
// MUL CTVLKT AJSNYX [2, 5, 6] [2, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        CTVLKT[i0*1+i1*2+i2*4] *= AJSNYX[i0*1+i2*2];}}}
// MUL CTVLKT CRJXSM [2, 5, 6] [2]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        CTVLKT[i0*1+i1*2+i2*4] *= CRJXSM[i0*1];}}}
// CPO WPNLQN [2, 5] 0.0
  WPNLQN= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    WPNLQN[i] = 0.0;
// MAR WPNLQN CTVLKT [2, 5] [2, 5, 6]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        WPNLQN[i0*1+i1*2] += CTVLKT[j0*4.0+i1*2.0+i0*1.0];}}}
// MUL FOHMFI WPNLQN [2, 4, 5] [2, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        FOHMFI[i0*1+i1*2+i2*4] *= WPNLQN[i0*1+i2*2];}}}
// CPO EWRGHL [2, 4] 0.0
  EWRGHL= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    EWRGHL[i] = 0.0;
// MAR EWRGHL FOHMFI [2, 4] [2, 4, 5]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        EWRGHL[i0*1+i1*2] += FOHMFI[j0*4.0+i1*2.0+i0*1.0];}}}
// MUL ZKWJBN EWRGHL [1, 2, 4] [2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        ZKWJBN[i0*1+i1*2+i2*4] *= EWRGHL[i1*1+i2*2];}}}
// MUL ZKWJBN USKGPZ [1, 2, 4] [1]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        ZKWJBN[i0*1+i1*2+i2*4] *= USKGPZ[i0*1];}}}
// MUL BAILMG WUIRBO [2, 4, 5] [2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BAILMG[i0*1+i1*2+i2*4] *= WUIRBO[i0*1+i1*2];}}}
// MUL BAILMG WPNLQN [2, 4, 5] [2, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BAILMG[i0*1+i1*2+i2*4] *= WPNLQN[i0*1+i2*2];}}}
// CPO KYZNKO ['6'] 0.0
  KYZNKO= new Float32Array(2);
  for(i=0;i<2;i++)
    KYZNKO[i] = 0.0;
// MAR KYZNKO BPTROO [6] [2, 5, 6]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      for (j1=0;j1<2;j1++){
        KYZNKO[i0*1] += BPTROO[i0*4.0+j1*2.0+j0*1.0];}}}
// NOR KYZNKO bronchitis?
  sum = 0.0
  for (i0=0; i0 <KYZNKO.length;i0++){
    sum +=KYZNKO[i0];}
  for (i0=0; i0 <KYZNKO.length;i0++){
    KYZNKO[i0]/=sum;}
  res['bronchitis?']=KYZNKO;
// CPO TGEOIG ['1'] 0.0
  TGEOIG= new Float32Array(2);
  for(i=0;i<2;i++)
    TGEOIG[i] = 0.0;
// MAR TGEOIG ZKWJBN [1] [1, 2, 4]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      for (j1=0;j1<2;j1++){
        TGEOIG[i0*1] += ZKWJBN[j1*4.0+j0*2.0+i0*1.0];}}}
// NOR TGEOIG tuberculosis?
  sum = 0.0
  for (i0=0; i0 <TGEOIG.length;i0++){
    sum +=TGEOIG[i0];}
  for (i0=0; i0 <TGEOIG.length;i0++){
    TGEOIG[i0]/=sum;}
  res['tuberculosis?']=TGEOIG;
// CPO DKGGPX ['4'] 0.0
  DKGGPX= new Float32Array(2);
  for(i=0;i<2;i++)
    DKGGPX[i] = 0.0;
// MAR DKGGPX BAILMG [4] [2, 4, 5]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      for (j1=0;j1<2;j1++){
        DKGGPX[i0*1] += BAILMG[j1*4.0+i0*2.0+j0*1.0];}}}
// NOR DKGGPX lung_cancer?
  sum = 0.0
  for (i0=0; i0 <DKGGPX.length;i0++){
    sum +=DKGGPX[i0];}
  for (i0=0; i0 <DKGGPX.length;i0++){
    DKGGPX[i0]/=sum;}
  res['lung_cancer?']=DKGGPX;
// CPO AEHOAR [2, 3] 1.0
  AEHOAR= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    AEHOAR[i] = 1.0;
// CPO WFIQMC [2, 6, 7] 1.0
  WFIQMC= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    WFIQMC[i] = 1.0;
// CPO JDYVBE [0, 1] 1.0
  JDYVBE= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    JDYVBE[i] = 1.0;
// CPO YGJAAF [1, 2, 4] 1.0
  YGJAAF= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    YGJAAF[i] = 1.0;
// CPO BNCDAO [2, 5, 6] 1.0
  BNCDAO= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    BNCDAO[i] = 1.0;
// CPO EAZTJN [2, 4, 5] 1.0
  EAZTJN= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    EAZTJN[i] = 1.0;
// MUC JDYVBE 0 [0, 1]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      JDYVBE[i0*1+i1*2] *= P0sachant[i0*1.0];}}
// MUC JDYVBE 1 [0, 1]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      JDYVBE[i0*1+i1*2] *= P1sachant0[i0*2.0+i1*1.0];}}
// MUC YGJAAF 2 [1, 2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        YGJAAF[i0*1+i1*2+i2*4] *= P2sachant1_4[i0*4.0+i2*2.0+i1*1.0];}}}
// MUC AEHOAR 3 [2, 3]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      AEHOAR[i0*1+i1*2] *= P3sachant2[i0*2.0+i1*1.0];}}
// MUC EAZTJN 4 [2, 4, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        EAZTJN[i0*1+i1*2+i2*4] *= P4sachant5[i2*2.0+i1*1.0];}}}
// MUC BNCDAO 5 [2, 5, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BNCDAO[i0*1+i1*2+i2*4] *= P5sachant[i1*1.0];}}}
// MUC BNCDAO 6 [2, 5, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BNCDAO[i0*1+i1*2+i2*4] *= P6sachant5[i1*2.0+i2*1.0];}}}
// MUC WFIQMC 7 [2, 6, 7]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        WFIQMC[i0*1+i1*2+i2*4] *= P7sachant6_2[i0*4.0+i1*2.0+i2*1.0];}}}
// ASE smoking? EV_5 0 evs.get([5, 'smoking?'][1])
  EV_5= new Float32Array(evs['smoking?']);
// ASE visit_to_Asia? EV_0 0 evs.get([0, 'visit_to_Asia?'][1])
  EV_0= new Float32Array(evs['visit_to_Asia?']);
// ASE dyspnoea? EV_7 0 evs.get([7, 'dyspnoea?'][1])
  EV_7= new Float32Array(evs['dyspnoea?']);
// ASE positive_XraY? EV_3 0 evs.get([3, 'positive_XraY?'][1])
  EV_3= new Float32Array(evs['positive_XraY?']);
// MUL JDYVBE EV_0 [0, 1] ['0']
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
    JDYVBE[i0*1+i1*2] *= EV_0[i0*1];}}
// MUL AEHOAR EV_3 [2, 3] ['3']
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
    AEHOAR[i0*1+i1*2] *= EV_3[i1*1];}}
// MUL BNCDAO EV_5 [2, 5, 6] ['5']
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BNCDAO[i0*1+i1*2+i2*4] *= EV_5[i1*1];}}}
// MUL WFIQMC EV_7 [2, 6, 7] ['7']
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        WFIQMC[i0*1+i1*2+i2*4] *= EV_7[i2*1];}}}
// CPO GGVLBR [2, 5, 6] 1.0
  GGVLBR= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    GGVLBR[i] = 1.0;
// MUL GGVLBR BNCDAO [2, 5, 6] [2, 5, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        GGVLBR[i0*1+i1*2+i2*4] *= BNCDAO[i0*1+i1*2+i2*4];}}}
// CPO HWAKVR [2, 4, 5] 1.0
  HWAKVR= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    HWAKVR[i] = 1.0;
// MUL HWAKVR EAZTJN [2, 4, 5] [2, 4, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        HWAKVR[i0*1+i1*2+i2*4] *= EAZTJN[i0*1+i1*2+i2*4];}}}
// CPO YMVGTO [1, 2, 4] 1.0
  YMVGTO= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    YMVGTO[i] = 1.0;
// MUL YMVGTO YGJAAF [1, 2, 4] [1, 2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        YMVGTO[i0*1+i1*2+i2*4] *= YGJAAF[i0*1+i1*2+i2*4];}}}
// CPO WSFHII [2, 4, 5] 1.0
  WSFHII= new Float32Array(2*2*2);
  for(i=0;i<2*2*2;i++)
    WSFHII[i] = 1.0;
// MUL WSFHII EAZTJN [2, 4, 5] [2, 4, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        WSFHII[i0*1+i1*2+i2*4] *= EAZTJN[i0*1+i1*2+i2*4];}}}
// CPO CSWWPQ [2, 6] 0.0
  CSWWPQ= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    CSWWPQ[i] = 0.0;
// MAR CSWWPQ WFIQMC [2, 6] [2, 6, 7]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        CSWWPQ[i0*1+i1*2] += WFIQMC[j0*4.0+i1*2.0+i0*1.0];}}}
// MUL BNCDAO CSWWPQ [2, 5, 6] [2, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BNCDAO[i0*1+i1*2+i2*4] *= CSWWPQ[i0*1+i2*2];}}}
// CPO VXCGSR [1] 0.0
  VXCGSR= new Float32Array(2);
  for(i=0;i<2;i++)
    VXCGSR[i] = 0.0;
// MAR VXCGSR JDYVBE [1] [0, 1]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      VXCGSR[i0*1] += JDYVBE[i0*2.0+j0*1.0];}}
// MUL YGJAAF VXCGSR [1, 2, 4] [1]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        YGJAAF[i0*1+i1*2+i2*4] *= VXCGSR[i0*1];}}}
// CPO KTJKEW [2, 4] 0.0
  KTJKEW= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    KTJKEW[i] = 0.0;
// MAR KTJKEW YGJAAF [2, 4] [1, 2, 4]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        KTJKEW[i0*1+i1*2] += YGJAAF[i1*4.0+i0*2.0+j0*1.0];}}}
// MUL EAZTJN KTJKEW [2, 4, 5] [2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        EAZTJN[i0*1+i1*2+i2*4] *= KTJKEW[i0*1+i1*2];}}}
// CPO MXDSGW [2, 5] 0.0
  MXDSGW= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    MXDSGW[i] = 0.0;
// MAR MXDSGW EAZTJN [2, 5] [2, 4, 5]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        MXDSGW[i0*1+i1*2] += EAZTJN[i1*4.0+j0*2.0+i0*1.0];}}}
// MUL BNCDAO MXDSGW [2, 5, 6] [2, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BNCDAO[i0*1+i1*2+i2*4] *= MXDSGW[i0*1+i1*2];}}}
// CPO YGFUVN [2] 0.0
  YGFUVN= new Float32Array(2);
  for(i=0;i<2;i++)
    YGFUVN[i] = 0.0;
// MAR YGFUVN AEHOAR [2] [2, 3]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      YGFUVN[i0*1] += AEHOAR[j0*2.0+i0*1.0];}}
// MUL BNCDAO YGFUVN [2, 5, 6] [2]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        BNCDAO[i0*1+i1*2+i2*4] *= YGFUVN[i0*1];}}}
// MUL GGVLBR CSWWPQ [2, 5, 6] [2, 6]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        GGVLBR[i0*1+i1*2+i2*4] *= CSWWPQ[i0*1+i2*2];}}}
// MUL GGVLBR YGFUVN [2, 5, 6] [2]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        GGVLBR[i0*1+i1*2+i2*4] *= YGFUVN[i0*1];}}}
// CPO QSGZER [2, 5] 0.0
  QSGZER= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    QSGZER[i] = 0.0;
// MAR QSGZER GGVLBR [2, 5] [2, 5, 6]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        QSGZER[i0*1+i1*2] += GGVLBR[j0*4.0+i1*2.0+i0*1.0];}}}
// MUL HWAKVR QSGZER [2, 4, 5] [2, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        HWAKVR[i0*1+i1*2+i2*4] *= QSGZER[i0*1+i2*2];}}}
// CPO PIWTDS [2, 4] 0.0
  PIWTDS= new Float32Array(2*2);
  for(i=0;i<2*2;i++)
    PIWTDS[i] = 0.0;
// MAR PIWTDS HWAKVR [2, 4] [2, 4, 5]
  for (i0=0;i0<2;i0++){
    for (i1=0;i1<2;i1++){
      for (j0=0;j0<2;j0++){
        PIWTDS[i0*1+i1*2] += HWAKVR[j0*4.0+i1*2.0+i0*1.0];}}}
// MUL YMVGTO PIWTDS [1, 2, 4] [2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        YMVGTO[i0*1+i1*2+i2*4] *= PIWTDS[i1*1+i2*2];}}}
// MUL YMVGTO VXCGSR [1, 2, 4] [1]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        YMVGTO[i0*1+i1*2+i2*4] *= VXCGSR[i0*1];}}}
// MUL WSFHII KTJKEW [2, 4, 5] [2, 4]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        WSFHII[i0*1+i1*2+i2*4] *= KTJKEW[i0*1+i1*2];}}}
// MUL WSFHII QSGZER [2, 4, 5] [2, 5]
  for (i0=0; i0<2;i0++){
    for (i1=0; i1<2;i1++){
      for (i2=0; i2<2;i2++){
        WSFHII[i0*1+i1*2+i2*4] *= QSGZER[i0*1+i2*2];}}}
// CPO VLOCOK ['6'] 0.0
  VLOCOK= new Float32Array(2);
  for(i=0;i<2;i++)
    VLOCOK[i] = 0.0;
// MAR VLOCOK BNCDAO [6] [2, 5, 6]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      for (j1=0;j1<2;j1++){
        VLOCOK[i0*1] += BNCDAO[i0*4.0+j1*2.0+j0*1.0];}}}
// NOR VLOCOK bronchitis?
  sum = 0.0
  for (i0=0; i0 <VLOCOK.length;i0++){
    sum +=VLOCOK[i0];}
  for (i0=0; i0 <VLOCOK.length;i0++){
    VLOCOK[i0]/=sum;}
  res['bronchitis?']=VLOCOK;
// CPO PKXTXJ ['1'] 0.0
  PKXTXJ= new Float32Array(2);
  for(i=0;i<2;i++)
    PKXTXJ[i] = 0.0;
// MAR PKXTXJ YMVGTO [1] [1, 2, 4]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      for (j1=0;j1<2;j1++){
        PKXTXJ[i0*1] += YMVGTO[j1*4.0+j0*2.0+i0*1.0];}}}
// NOR PKXTXJ tuberculosis?
  sum = 0.0
  for (i0=0; i0 <PKXTXJ.length;i0++){
    sum +=PKXTXJ[i0];}
  for (i0=0; i0 <PKXTXJ.length;i0++){
    PKXTXJ[i0]/=sum;}
  res['tuberculosis?']=PKXTXJ;
// CPO GSJZQN ['4'] 0.0
  GSJZQN= new Float32Array(2);
  for(i=0;i<2;i++)
    GSJZQN[i] = 0.0;
// MAR GSJZQN WSFHII [4] [2, 4, 5]
  for (i0=0;i0<2;i0++){
    for (j0=0;j0<2;j0++){
      for (j1=0;j1<2;j1++){
        GSJZQN[i0*1] += WSFHII[j1*4.0+i0*2.0+j0*1.0];}}}
// NOR GSJZQN lung_cancer?
  sum = 0.0
  for (i0=0; i0 <GSJZQN.length;i0++){
    sum +=GSJZQN[i0];}
  for (i0=0; i0 <GSJZQN.length;i0++){
    GSJZQN[i0]/=sum;}
  res['lung_cancer?']=GSJZQN;
  return res;
}
res=getProbaForAsia({
  "smoking?" : [..],
  "visit_to_Asia?" : [..],
  "dyspnoea?" : [..],
  "positive_XraY?" : [..]
});
      
for (k in res) {
  st=""+k+" => ";
  for (i=0;i<res[k].length;i++) {
    st+=i+" : "+  res[k][i]+" | "
  }
console.log(st)
}
    